# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)


require "open-uri"
User.destroy_all
Post.destroy_all

user01 = User.create!({username: "demouser", password: "demouser", email: "demouser"})
user01.profile_pic.attach(io: open("https://qadlee-dev.s3-us-west-1.amazonaws.com/profile-pics/dog-pp.jpg"), filename: "dog-pp.jpg")
user02 = User.create!({username: "abigailthorn", password: "demouser", email: "abigailthorn"})
user02.profile_pic.attach(io: open("https://qadlee-dev.s3-us-west-1.amazonaws.com/profile-pics/49-pp.jpg"), filename: "49-pp.jpg")
user03 = User.create!({username: "mrhandsome", password: "demouser", email: "mrhandsome"})
user03.profile_pic.attach(io: open("https://qadlee-dev.s3-us-west-1.amazonaws.com/profile-pics/disney-pp.jpg"), filename: "disney-pp.jpg")
user04 = User.create!({username: "wheresmycat", password: "demouser", email: "wheresmycat"})
user04.profile_pic.attach(io: open("https://qadlee-dev.s3-us-west-1.amazonaws.com/profile-pics/dog-pp.jpg"), filename: "dog-pp.jpg")
user05 = User.create!({username: "unlosted", password: "demouser", email: "unlosted"})
user05.profile_pic.attach(io: open("https://qadlee-dev.s3-us-west-1.amazonaws.com/profile-pics/emoji-pp.png"), filename: "emoji-pp.png")
user06 = User.create!({username: "hellogoodbye", password: "demouser", email: "hellogoodbye"})
user06.profile_pic.attach(io: open("https://qadlee-dev.s3-us-west-1.amazonaws.com/profile-pics/flower-pp.jpg"), filename: "flower-pp.jpg")
user07 = User.create!({username: "mcdreamy", password: "demouser", email: "mcdreamy"})
user07.profile_pic.attach(io: open("https://qadlee-dev.s3-us-west-1.amazonaws.com/profile-pics/forest-pp.jpg"), filename: "forest-pp.jpg")
user08 = User.create!({username: "randolf", password: "demouser", email: "randolf"})
user08.profile_pic.attach(io: open("https://qadlee-dev.s3-us-west-1.amazonaws.com/profile-pics/hogwarts-pp.jpg"), filename: "hogwarts-pp.jpg")
user09 = User.create!({username: "wakawaka", password: "demouser", email: "wakawaka"})
user09.profile_pic.attach(io: open("https://qadlee-dev.s3-us-west-1.amazonaws.com/profile-pics/indian-pp.jpg"), filename: "indian-pp.jpg")
user10 = User.create!({username: "sherlokhomie", password: "demouser", email: "sherlokhomie"})
user10.profile_pic.attach(io: open("https://qadlee-dev.s3-us-west-1.amazonaws.com/profile-pics/jeep-pp.jpg"), filename: "jeep-pp.jpg")
user11 = User.create!({username: "majorflex", password: "demouser", email: "majorflex"})
user11.profile_pic.attach(io: open("https://qadlee-dev.s3-us-west-1.amazonaws.com/profile-pics/lyonel-richie-pp.jpg"), filename: "lyonel-richie-pp.jpg")
user12 = User.create!({username: "princesspenelope", password: "demouser", email: "princesspenelope"})
user12.profile_pic.attach(io: open("https://qadlee-dev.s3-us-west-1.amazonaws.com/profile-pics/mm-pp.jpg"), filename: "mm-pp.jpg")
user13 = User.create!({username: "almaguapo", password: "demouser", email: "almaguapo"})
user13.profile_pic.attach(io: open("https://qadlee-dev.s3-us-west-1.amazonaws.com/profile-pics/moon-pp.jpg"), filename: "moon-pp.jpg")
user14 = User.create!({username: "usernametaken", password: "demouser", email: "usernametaken"})
user14.profile_pic.attach(io: open("https://qadlee-dev.s3-us-west-1.amazonaws.com/profile-pics/randy-pp.jpg"), filename: "randy-pp.jpg")
user15 = User.create!({username: "seedthis", password: "demouser", email: "seedthis"})
user15.profile_pic.attach(io: open("https://qadlee-dev.s3-us-west-1.amazonaws.com/profile-pics/shrek-pp.png"), filename: "shrek-pp.png")
user16 = User.create!({username: "rubyrails", password: "demouser", email: "rubyrails"})
user16.profile_pic.attach(io: open("https://qadlee-dev.s3-us-west-1.amazonaws.com/profile-pics/smiling-girl-pp.png"), filename: "smiling-girl-pp.png")
user17 = User.create!({username: "scriptofjava", password: "demouser", email: "scriptofjava"})
user17.profile_pic.attach(io: open("https://qadlee-dev.s3-us-west-1.amazonaws.com/profile-pics/sunset.jpg"), filename: "sunset-pp.jpg")
user18 = User.create!({username: "unclephil", password: "demouser", email: "unclephil"})
user18.profile_pic.attach(io: open("https://qadlee-dev.s3-us-west-1.amazonaws.com/profile-pics/vitruvian-pp.jpg"), filename: "vituvian-pp.jpg")
user19 = User.create!({username: "themoose", password: "demouser", email: "themoose"})
user19.profile_pic.attach(io: open("https://qadlee-dev.s3-us-west-1.amazonaws.com/profile-pics/walle-pp.jpg"), filename: "walle-pp.jpg")
user20 = User.create!({username: "socioholic", password: "demouser", email: "socioholic"})
user20.profile_pic.attach(io: open("https://qadlee-dev.s3-us-west-1.amazonaws.com/profile-pics/woman-drawong-pp.jpg"), filename: "woman-drawong-pp.jpg")

# ------text--------

# post01 = Post.create!({post_type: "text", title: "Best Day Ever", body:"Yesterday I went to the mall and realized that all the pretzels were on sale for national pretzel day!!", author_id: user01.id})
# post02 = Post.create!({post_type: "text", title: "Hear Me Out", body:"What if we all decided to make Fridays part of the weekend??!?!?! Lets give that a try yea?", author_id: user02.id})
# post03 = Post.create!({post_type: "text", title: "Is This True?", body:"My friend told me that if you travel around the globe you'll actually end up right back where you started and my mind is BLOWN", author_id: user03.id})
# post04 = Post.create!({post_type: "text", title: "Coding is Hard", body:"I started coding about 3 months and realized theres just too much to learn. Like just seeding a database takes about 600 days", author_id: user04.id})
# post05 = Post.create!({post_type: "text", title: "A Quick Rant", body:"I started working in retail when I was 16 years old and realized that most people dont have annnyyyy patience whatsoever when it comes to retail workers. Like zero patience. So the next day I decided to tell my boss that I quit and not I'm on my way to becoming a certified massage therapist. Chase your dreams kids!", author_id: user05.id})
# post06 = Post.create!({post_type: "text", title: "Inventing a New Color", body:"Lately I've been thinking about inventing a new color but I dont even know where to start", author_id: user06.id})
# post07 = Post.create!({post_type: "text", title: "How Much Woord ", body:"Would a wood chuck chuck if a wood chuck could chuck wood???", author_id: user07.id})
# post08 = Post.create!({post_type: "text", title: "Next Year", body:"Don't worry guys, once we make it past 2020 things are gonna be allllllright", author_id: user08.id})
# post09 = Post.create!({post_type: "text", title: "Lost my Sponge", body:"I lost my sponge ):", author_id: user09.id})
# post10 = Post.create!({post_type: "text", title: "First Post", body:"Hey guys! This is my first post on qadlee and I'm hoping to make a lot of new and amazing friends on here!", author_id: user10.id})

# #------image--------

# post11 = Post.create!({post_type: "image", title: "My New Piece (:", author_id: user11.id})
# post11.photo.attach(io: open("https://qadlee-dev.s3-us-west-1.amazonaws.com/image-post/art.jpg"), filename: "art.jpg")
# post12 = Post.create!({post_type: "image", title: "Dream Car", author_id: user12.id })
# post12.photo.attach(io: open("https://qadlee-dev.s3-us-west-1.amazonaws.com/image-post/car.jpg"), filename: "car.jpg")
# post13 = Post.create!({post_type: "image", title: "He's Getting So Old!!", author_id: user13.id })
# post13.photo.attach(io: open("https://qadlee-dev.s3-us-west-1.amazonaws.com/image-post/cat.jpg"), filename: "cat.jpg")
# post14 = Post.create!({post_type: "image", title: "Goodbye Diet", author_id: user14.id })
# post14.photo.attach(io: open("https://qadlee-dev.s3-us-west-1.amazonaws.com/image-post/food.jpg"), filename: "food.jpg")
# post15 = Post.create!({post_type: "image", title: "Wanderer", author_id: user15.id})
# post15.photo.attach(io: open("https://qadlee-dev.s3-us-west-1.amazonaws.com/image-post/forest.jpeg"), filename: "forest.jpg")
# post16 = Post.create!({post_type: "image", title: "Lets go Team!!!", author_id: user16.id })
# post16.photo.attach(io: open("https://qadlee-dev.s3-us-west-1.amazonaws.com/image-post/game.jpg"), filename: "game.jpg")
# post17 = Post.create!({post_type: "image", title: "Should I Get This?", author_id: user17.id})
# post17.photo.attach(io: open("https://qadlee-dev.s3-us-west-1.amazonaws.com/image-post/hair.jpg"), filename: "hair.jpg")
# post18 = Post.create!({post_type: "image", title: "Officially Going on Vacay", author_id: user18.id})
# post18.photo.attach(io: open("https://qadlee-dev.s3-us-west-1.amazonaws.com/image-post/passport.jpg"), filename: "passport.jpg")
# post19 = Post.create!({post_type: "image", title: "Last Day of Summer", author_id: user19.id})
# post19.photo.attach(io: open("https://qadlee-dev.s3-us-west-1.amazonaws.com/image-post/sunset-pp.jpg"), filename: "sunset.jpg")
# post20 = Post.create!({post_type: "image", title: "New Camera is Great", author_id: user20.id })
# post20.photo.attach(io: open("https://qadlee-dev.s3-us-west-1.amazonaws.com/image-post/travel.jpg"), filename: "travel.jpg")

# #------quote--------

# post21 = Post.create!({post_type: "quote", title: "'He who runs, shall not walk'", body: "--Usain Bolt", author_id: user01.id})
# post22 = Post.create!({post_type: "quote", title: "'Life is like a flower, smell it'", body: "--some botonist", author_id: user02.id})
# post23 = Post.create!({post_type: "quote", title: "'When everything is right, whats left?'", body: "--Freud", author_id: user03.id})
# post24 = Post.create!({post_type: "quote", title: "'Everyday holds a new tomorrow'", body: "--Ghandi", author_id: user04.id})
# post25 = Post.create!({post_type: "quote", title: "'Freedom is not a privilege, it is a right'", body: "--Martin Luther King Jr.", author_id: user05.id})
# post26 = Post.create!({post_type: "quote", title: "'Today is a gift, that's why its called the present'", body: "--Abraham Lincoln", author_id: user06.id})
# post27 = Post.create!({post_type: "quote", title: "'When time runs out, whp will be there to watch?'", body: "--Anand Shirma", author_id:user07.id})
# post28 = Post.create!({post_type: "quote", title: "'Even a broken clock is right twice a day'", body: "--Walter White", author_id: user08.id})
# post29 = Post.create!({post_type: "quote", title: "'A cup of tea without tea is just a cup'", body: "--Rupi Kaur", author_id: user09.id})
# post30 = Post.create!({post_type: "quote", title: "'Dont stand around and wait, take what you deserve'", body: "--Steve Kerr", author_id: user10.id})

# # ------link--------

# post31 = Post.create!({post_type: "link", title: "My New Addiction", body: "pixilart.com", author_id: user11.id})
# post32 = Post.create!({post_type: "link", title: "When people ask how I know eveyrthing >>", body: "wikipedia.com", author_id: user12.id})
# post33 = Post.create!({post_type: "link", title: "Games aren't just for kids", body: "miniclip.com", author_id: user13.id})
# post34 = Post.create!({post_type: "link", title: "Finally found a new job!!", body: "indeed.com", author_id: user14.id})
# post35 = Post.create!({post_type: "link", title: "Soooo much better than a hotel", body: "airbnb.com", author_id: user15.id})
# post36 = Post.create!({post_type: "link", title: "Any Recommendations?", body: "expedia.com", author_id: user16.id})
# post37 = Post.create!({post_type: "link", title: "add me everyone!", body: "twitter.com", author_id: user17.id})
# post38 = Post.create!({post_type: "link", title: "Best Cake Recipes", body: "recipe.com", author_id: user18.id})
# post39 = Post.create!({post_type: "link", title: "Should I get this car?", body: "ford.com", author_id: user19.id})
# post40 = Post.create!({post_type: "link", title: "I love the new iPhone", body: "apple.com", author_id: user20.id})

# # ------chat--------

# post41 = Post.create!({post_type: "chat", title: "At The Doctor", body: "me: Hey doc, I think I'm sick doctor: oh let me see whats wrong me: thanks", author_id: user01.id})
# post42 = Post.create!({post_type: "chat", title: "Whys my dad like this", body: "dad: Hey hon, did we ever turn off the stove mom: I dont think so", author_id: user02.id})
# post43 = Post.create!({post_type: "chat", title: "The Frog and The Toad", body: "frog: ribbit ribbit toad: its RIB it you idiot", author_id: user03.id})
# post44 = Post.create!({post_type: "chat", title: "Realization", body: "me: I think Im sick therapist: no youre the SICKEST :P", author_id: user04.id})
# post45 = Post.create!({post_type: "chat", title: "Darwins theory", body: "Darwin: why do you have legs? fish: Im different", author_id: user05.id})
# post46 = Post.create!({post_type: "chat", title: "me IRL", body: "friend: whys the sky blue? me: Its been feeling a little down friend: oh", author_id: user06.id})
# post47 = Post.create!({post_type: "chat", title: "typical", body: "bouncer: hey you cant be in here fox: Ok Ill just exit then", author_id: user07.id})
# post48 = Post.create!({post_type: "chat", title: "Amazon customer support", body: "amazon: We see you purchased a fridge, would you like us to suggest 30 other fridges to go with that??!?!?!", author_id: user08.id})
# post49 = Post.create!({post_type: "chat", title: "A duet", body: "Romeo: O Juliet! Juliet: O Romeo! Romeo: Shall we wed????", author_id: user09.id})
# post50 = Post.create!({post_type: "chat", title: "@ the mechanic", body: "mechanic: looks like you need a new engine me: thanks", author_id: user10.id})

# # ------audio--------

# post51 = Post.create!({post_type: "audio", title: "What all commericals sound like", author_id: user11.id})
# post51.photo.attach(io: open("https://qadlee-dev.s3-us-west-1.amazonaws.com/audio-post/commercial.mp3"), filename: "commercial.mp3")
# post52 = Post.create!({post_type: "audio", title: "My new piece!", author_id: user12.id})
# post52.photo.attach(io: open("https://qadlee-dev.s3-us-west-1.amazonaws.com/audio-post/drama.mp3"), filename: "drama.mp3")
# post53 = Post.create!({post_type: "audio", title: "If you need to cheer up (:", author_id: user13.id})
# post53.photo.attach(io: open("https://qadlee-dev.s3-us-west-1.amazonaws.com/audio-post/happy.mp3"), filename: "happy.mp3")
# post54 = Post.create!({post_type: "audio", title: "GoT intro still gets me", author_id: user14.id})
# post54.photo.attach(io: open("https://qadlee-dev.s3-us-west-1.amazonaws.com/audio-post/hero.mp3"), filename: "hero.mp3")
# post55 = Post.create!({post_type: "audio", title: "this plays in my head all day", author_id: user15.id})
# post55.photo.attach(io: open("https://qadlee-dev.s3-us-west-1.amazonaws.com/audio-post/myserious.mp3"), filename: "myserious.mp3")
# post56 = Post.create!({post_type: "audio", title: "new favorite song!!", author_id: user16.id})
# post56.photo.attach(io: open("https://qadlee-dev.s3-us-west-1.amazonaws.com/audio-post/news.mp3"), filename: "news.mp3")
# post57 = Post.create!({post_type: "audio", title: "Finally playing the piano again", author_id: user17.id})
# post57.photo.attach(io: open("https://qadlee-dev.s3-us-west-1.amazonaws.com/audio-post/piano.mp3"), filename: "piano.mp3")
# post58 = Post.create!({post_type: "audio", title: "I can def rap to this", author_id: user18.id})
# post58.photo.attach(io: open("https://qadlee-dev.s3-us-west-1.amazonaws.com/audio-post/rap.mp3"), filename: "rap.mp3")
# post59 = Post.create!({post_type: "audio", title: "Music to relax to (:", author_id: user19.id})
# post59.photo.attach(io: open("https://qadlee-dev.s3-us-west-1.amazonaws.com/audio-post/study.mp3"), filename: "study.mp3")
# post60 = Post.create!({post_type: "audio", title: "LETS DANCE", author_id: user20.id})
# post60.photo.attach(io: open("https://qadlee-dev.s3-us-west-1.amazonaws.com/audio-post/techno.mp3"), filename: "techno.mp3")

# # ------video--------

# post61 = Post.create!({post_type: "video", title: "New camera!!", author_id: user01.id})
# post61.photo.attach(io: open("https://qadlee-dev.s3-us-west-1.amazonaws.com/video-post/beach.mp4"), filename: "beach.mp4")
# post62 = Post.create!({post_type: "video", title: "Whys this so peaceful", author_id: user02.id})
# post62.photo.attach(io: open("https://qadlee-dev.s3-us-west-1.amazonaws.com/video-post/clouds.mp4"), filename: "clouds.mp4")
# post63 = Post.create!({post_type: "video", title: "Loving my new job!", author_id: user03.id})
# post63.photo.attach(io: open("https://qadlee-dev.s3-us-west-1.amazonaws.com/video-post/coffee.mp4"), filename: "coffee.mp4")
# post64 = Post.create!({post_type: "video", title: "Nebraska is soooo underated", author_id: user04.id})
# post64.photo.attach(io: open("https://qadlee-dev.s3-us-west-1.amazonaws.com/video-post/country.mp4"), filename: "country.mp4")
# post65 = Post.create!({post_type: "video", title: "morning stretch (:", author_id: user05.id})
# post65.photo.attach(io: open("https://qadlee-dev.s3-us-west-1.amazonaws.com/video-post/fog.mp4"), filename: "fog.mp4")
# post66 = Post.create!({post_type: "video", title: "Finally got to take her out!", author_id: user06.id})
# post66.photo.attach(io: open("https://qadlee-dev.s3-us-west-1.amazonaws.com/video-post/jeep.mp4"), filename: "jeep.p4")
# post67 = Post.create!({post_type: "video", title: "happy anniversary my love!", author_id: user07.id})
# post67.photo.attach(io: open("https://qadlee-dev.s3-us-west-1.amazonaws.com/video-post/love.mp4"), filename: "love.mp4")
# post68 = Post.create!({post_type: "video", title: "TBT to my first time on stage", author_id: user08.id})
# post68.photo.attach(io: open("https://qadlee-dev.s3-us-west-1.amazonaws.com/video-post/mic.mp4"), filename: "mic.mp4")
# post69 = Post.create!({post_type: "video", title: "Enjoy the moment!", author_id: user09.id})
# post69.photo.attach(io: open("https://qadlee-dev.s3-us-west-1.amazonaws.com/video-post/paris.mp4"), filename: "paris.mp4")
# post70 = Post.create!({post_type: "video", title: "ok now im hungry", author_id: user10.id})
# post70.photo.attach(io: open("https://qadlee-dev.s3-us-west-1.amazonaws.com/video-post/pizza.mp4"), filename: "pizza.mp4")


# ------text--------

post62 = Post.create!({post_type: "video", title: "Whys this so peaceful", author_id: user02.id})
post62.photo.attach(io: open("https://qadlee-dev.s3-us-west-1.amazonaws.com/video-post/clouds.mp4"), filename: "clouds.mp4")
post01 = Post.create!({post_type: "text", title: "Best Day Ever", body:"Yesterday I went to the mall and realized that all the pretzels were on sale for national pretzel day!!", author_id: user01.id})
post51 = Post.create!({post_type: "audio", title: "What all commericals sound like", author_id: user11.id})
post51.photo.attach(io: open("https://qadlee-dev.s3-us-west-1.amazonaws.com/audio-post/commercial.mp3"), filename: "commercial.mp3")
post45 = Post.create!({post_type: "chat", title: "Darwins theory", body: "Darwin: why do you have legs? fish: Im different", author_id: user05.id})
post12 = Post.create!({post_type: "image", title: "Dream Car", author_id: user12.id })
post12.photo.attach(io: open("https://qadlee-dev.s3-us-west-1.amazonaws.com/image-post/car.jpg"), filename: "car.jpg")
post35 = Post.create!({post_type: "link", title: "Soooo much better than a hotel", body: "www.airbnb.com", author_id: user15.id})
post46 = Post.create!({post_type: "chat", title: "me IRL", body: "friend: whys the sky blue? me: Its been feeling a little down friend: oh", author_id: user06.id})
post63 = Post.create!({post_type: "video", title: "Loving my new job!", author_id: user03.id})
post63.photo.attach(io: open("https://qadlee-dev.s3-us-west-1.amazonaws.com/video-post/coffee.mp4"), filename: "coffee.mp4")
post57 = Post.create!({post_type: "audio", title: "Finally playing the piano again", author_id: user17.id})
post57.photo.attach(io: open("https://qadlee-dev.s3-us-west-1.amazonaws.com/audio-post/piano.mp3"), filename: "piano.mp3")
post58 = Post.create!({post_type: "audio", title: "I can def rap to this", author_id: user18.id})
post58.photo.attach(io: open("https://qadlee-dev.s3-us-west-1.amazonaws.com/audio-post/rap.mp3"), filename: "rap.mp3")
post11 = Post.create!({post_type: "image", title: "My New Piece (:", author_id: user11.id})
post11.photo.attach(io: open("https://qadlee-dev.s3-us-west-1.amazonaws.com/image-post/art.jpg"), filename: "art.jpg")
post54 = Post.create!({post_type: "audio", title: "GoT intro still gets me", author_id: user14.id})
post54.photo.attach(io: open("https://qadlee-dev.s3-us-west-1.amazonaws.com/audio-post/hero.mp3"), filename: "hero.mp3")
post02 = Post.create!({post_type: "text", title: "Hear Me Out", body:"What if we all decided to make Fridays part of the weekend??!?!?! Lets give that a try yea?", author_id: user02.id})
post03 = Post.create!({post_type: "text", title: "Is This True?", body:"My friend told me that if you travel around the globe you'll actually end up right back where you started and my mind is BLOWN", author_id: user03.id})
post66 = Post.create!({post_type: "video", title: "Finally got to take her out!", author_id: user06.id})
post66.photo.attach(io: open("https://qadlee-dev.s3-us-west-1.amazonaws.com/video-post/jeep.mp4"), filename: "jeep.p4")
post22 = Post.create!({post_type: "quote", title: "'Life is like a flower, smell it'", body: "--some botonist", author_id: user02.id})
post04 = Post.create!({post_type: "text", title: "Coding is Hard", body:"I started coding about 3 months and realized theres just too much to learn. Like just seeding a database takes about 600 days", author_id: user04.id})
post69 = Post.create!({post_type: "video", title: "Enjoy the moment!", author_id: user09.id})
post69.photo.attach(io: open("https://qadlee-dev.s3-us-west-1.amazonaws.com/video-post/paris.mp4"), filename: "paris.mp4")
post44 = Post.create!({post_type: "chat", title: "Realization", body: "me: I think Im sick therapist: no youre the SICKEST :P", author_id: user04.id})
post19 = Post.create!({post_type: "image", title: "Last Day of Summer", author_id: user19.id})
post19.photo.attach(io: open("https://qadlee-dev.s3-us-west-1.amazonaws.com/image-post/sunset-pp.jpg"), filename: "sunset.jpg")
post53 = Post.create!({post_type: "audio", title: "If you need to cheer up (:", author_id: user13.id})
post53.photo.attach(io: open("https://qadlee-dev.s3-us-west-1.amazonaws.com/audio-post/happy.mp3"), filename: "happy.mp3")
post39 = Post.create!({post_type: "link", title: "Should I get this car?", body: "ford.com", author_id: user19.id})
post26 = Post.create!({post_type: "quote", title: "'Today is a gift, that's why its called the present'", body: "--Abraham Lincoln", author_id: user06.id})
post68 = Post.create!({post_type: "video", title: "TBT to my first time on stage", author_id: user08.id})
post68.photo.attach(io: open("https://qadlee-dev.s3-us-west-1.amazonaws.com/video-post/mic.mp4"), filename: "mic.mp4")
post21 = Post.create!({post_type: "quote", title: "'He who runs, shall not walk'", body: "--Usain Bolt", author_id: user01.id})
post17 = Post.create!({post_type: "image", title: "Should I Get This?", author_id: user17.id})
post17.photo.attach(io: open("https://qadlee-dev.s3-us-west-1.amazonaws.com/image-post/hair.jpg"), filename: "hair.jpg")
post43 = Post.create!({post_type: "chat", title: "The Frog and The Toad", body: "frog: ribbit ribbit toad: its RIB it you idiot", author_id: user03.id})
post33 = Post.create!({post_type: "link", title: "Games aren't just for kids", body: "miniclip.com", author_id: user13.id})
post52 = Post.create!({post_type: "audio", title: "My new piece!", author_id: user12.id})
post64 = Post.create!({post_type: "video", title: "Nebraska is soooo underated", author_id: user04.id})
post64.photo.attach(io: open("https://qadlee-dev.s3-us-west-1.amazonaws.com/video-post/country.mp4"), filename: "country.mp4")
post30 = Post.create!({post_type: "quote", title: "'Dont stand around and wait, take what you deserve'", body: "--Steve Kerr", author_id: user10.id})
post13 = Post.create!({post_type: "image", title: "He's Getting So Old!!", author_id: user13.id })
post13.photo.attach(io: open("https://qadlee-dev.s3-us-west-1.amazonaws.com/image-post/cat.jpg"), filename: "cat.jpg")
post25 = Post.create!({post_type: "quote", title: "'Freedom is not a privilege, it is a right'", body: "--Martin Luther King Jr.", author_id: user05.id})
post18 = Post.create!({post_type: "image", title: "Officially Going on Vacay", author_id: user18.id})
post18.photo.attach(io: open("https://qadlee-dev.s3-us-west-1.amazonaws.com/image-post/passport.jpg"), filename: "passport.jpg")
post38 = Post.create!({post_type: "link", title: "Best Cake Recipes", body: "recipe.com", author_id: user18.id})
post40 = Post.create!({post_type: "link", title: "I love the new iPhone", body: "apple.com", author_id: user20.id})
post37 = Post.create!({post_type: "link", title: "add me everyone!", body: "twitter.com", author_id: user17.id})
post21 = Post.create!({post_type: "quote", title: "'He who runs, shall not walk'", body: "--Usain Bolt", author_id: user01.id})
post05 = Post.create!({post_type: "text", title: "A Quick Rant", body:"I started working in retail when I was 16 years old and realized that most people dont have annnyyyy patience whatsoever when it comes to retail workers. Like zero patience. So the next day I decided to tell my boss that I quit and not I'm on my way to becoming a certified massage therapist. Chase your dreams kids!", author_id: user05.id})
post15 = Post.create!({post_type: "image", title: "Wanderer", author_id: user15.id})
post15.photo.attach(io: open("https://qadlee-dev.s3-us-west-1.amazonaws.com/image-post/forest.jpeg"), filename: "forest.jpg")
post56 = Post.create!({post_type: "audio", title: "new favorite song!!", author_id: user16.id})
post56.photo.attach(io: open("https://qadlee-dev.s3-us-west-1.amazonaws.com/audio-post/news.mp3"), filename: "news.mp3")
post06 = Post.create!({post_type: "text", title: "Inventing a New Color", body:"Lately I've been thinking about inventing a new color but I dont even know where to start", author_id: user06.id})
post14 = Post.create!({post_type: "image", title: "Goodbye Diet", author_id: user14.id })
post14.photo.attach(io: open("https://qadlee-dev.s3-us-west-1.amazonaws.com/image-post/food.jpg"), filename: "food.jpg")
post07 = Post.create!({post_type: "text", title: "How Much Woord ", body:"Would a wood chuck chuck if a wood chuck could chuck wood???", author_id: user07.id})
post08 = Post.create!({post_type: "text", title: "Next Year", body:"Don't worry guys, once we make it past 2020 things are gonna be allllllright", author_id: user08.id})
post67 = Post.create!({post_type: "video", title: "happy anniversary my love!", author_id: user07.id})
post67.photo.attach(io: open("https://qadlee-dev.s3-us-west-1.amazonaws.com/video-post/love.mp4"), filename: "love.mp4")
post20 = Post.create!({post_type: "image", title: "New Camera is Great", author_id: user20.id })
post20.photo.attach(io: open("https://qadlee-dev.s3-us-west-1.amazonaws.com/image-post/travel.jpg"), filename: "travel.jpg")
post31 = Post.create!({post_type: "link", title: "My New Addiction", body: "pixilart.com", author_id: user11.id})
post27 = Post.create!({post_type: "quote", title: "'When time runs out, whp will be there to watch?'", body: "--Anand Shirma", author_id:user07.id})
post34 = Post.create!({post_type: "link", title: "Finally found a new job!!", body: "indeed.com", author_id: user14.id})
post23 = Post.create!({post_type: "quote", title: "'When everything is right, whats left?'", body: "--Freud", author_id: user03.id})
post61 = Post.create!({post_type: "video", title: "New camera!!", author_id: user01.id})
post61.photo.attach(io: open("https://qadlee-dev.s3-us-west-1.amazonaws.com/video-post/beach.mp4"), filename: "beach.mp4")
post09 = Post.create!({post_type: "text", title: "Lost my Sponge", body:"I lost my sponge ):", author_id: user09.id})
post24 = Post.create!({post_type: "quote", title: "'Everyday holds a new tomorrow'", body: "--Ghandi", author_id: user04.id})
post47 = Post.create!({post_type: "chat", title: "typical", body: "bouncer: hey you cant be in here fox: Ok Ill just exit then", author_id: user07.id})
post70 = Post.create!({post_type: "video", title: "ok now im hungry", author_id: user10.id})
post70.photo.attach(io: open("https://qadlee-dev.s3-us-west-1.amazonaws.com/video-post/pizza.mp4"), filename: "pizza.mp4")
post55 = Post.create!({post_type: "audio", title: "this plays in my head all day", author_id: user15.id})
post55.photo.attach(io: open("https://qadlee-dev.s3-us-west-1.amazonaws.com/audio-post/myserious.mp3"), filename: "myserious.mp3")
post10 = Post.create!({post_type: "text", title: "First Post", body:"Hey guys! This is my first post on qadlee and I'm hoping to make a lot of new and amazing friends on here!", author_id: user10.id})
post32 = Post.create!({post_type: "link", title: "When people ask how I know eveyrthing >>", body: "wikipedia.com", author_id: user12.id})
post28 = Post.create!({post_type: "quote", title: "'Even a broken clock is right twice a day'", body: "--Walter White", author_id: user08.id})
post41 = Post.create!({post_type: "chat", title: "At The Doctor", body: "me: Hey doc, I think I'm sick doctor: oh let me see whats wrong me: thanks", author_id: user01.id})
post59 = Post.create!({post_type: "audio", title: "Music to relax to (:", author_id: user19.id})
post59.photo.attach(io: open("https://qadlee-dev.s3-us-west-1.amazonaws.com/audio-post/study.mp3"), filename: "study.mp3")
post36 = Post.create!({post_type: "link", title: "Any Recommendations?", body: "expedia.com", author_id: user16.id})
post16 = Post.create!({post_type: "image", title: "Lets go Team!!!", author_id: user16.id })
post16.photo.attach(io: open("https://qadlee-dev.s3-us-west-1.amazonaws.com/image-post/game.jpg"), filename: "game.jpg")
post42 = Post.create!({post_type: "chat", title: "Whys my dad like this", body: "dad: Hey hon, did we ever turn off the stove mom: I dont think so", author_id: user02.id})
post29 = Post.create!({post_type: "quote", title: "'A cup of tea without tea is just a cup'", body: "--Rupi Kaur", author_id: user09.id})
post49 = Post.create!({post_type: "chat", title: "A duet", body: "Romeo: O Juliet! Juliet: O Romeo! Romeo: Shall we wed????", author_id: user09.id})
post65 = Post.create!({post_type: "video", title: "morning stretch (:", author_id: user05.id})
post65.photo.attach(io: open("https://qadlee-dev.s3-us-west-1.amazonaws.com/video-post/fog.mp4"), filename: "fog.mp4")
post50 = Post.create!({post_type: "chat", title: "@ the mechanic", body: "mechanic: looks like you need a new engine me: thanks", author_id: user10.id})
post60 = Post.create!({post_type: "audio", title: "LETS DANCE", author_id: user20.id})
post60.photo.attach(io: open("https://qadlee-dev.s3-us-west-1.amazonaws.com/audio-post/techno.mp3"), filename: "techno.mp3")